# Generated by Django 5.2.7 on 2025-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diya', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diyas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
